### ISSUE TITLE
Tests are broken

### ISSUE THREAD

**Issue by amotl** [crate/pgjdbc#48]
### About
Even after GH-47, the tests are currently failing badly for me. GH-66 also demonstrates it on CI. Does anyone know the trick how to make them work?

```
mvn clean package
```

Currently, those errors are all over the place. Here are two samples.

```
java.sql.SQLException: No suitable driver found for jdbc:postgresql://localhost:5432/test
java.lang.NullPointerException: Cannot invoke "java.sql.Connection.createStatement()" because "con" is null
```

### Outlook
It would be sweet to make them work, also for being able to trust any updates submitted by Dependabot (GH-46) without further ado.

### Details
```java
testSupportsRefCursors(org.postgresql.test.jdbc42.SimpleJdbc42Test)  Time elapsed: 0.007 sec  <<< ERROR!
java.sql.SQLException: No suitable driver found for jdbc:postgresql://localhost:5432/test?ApplicationName=Driver Tests&loggerLevel=OFF&loggerFile=target/pgjdbc-tests.log
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:708)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:191)
	at org.postgresql.test.TestUtil.openDB(TestUtil.java:342)
	at org.postgresql.test.jdbc2.BaseTest4.setUp(BaseTest4.java:83)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```

```java
testGetLocalDateTime[binary = REGULAR](org.postgresql.test.jdbc42.GetObject310Test)  Time elapsed: 0.001 sec  <<< ERROR!
java.lang.NullPointerException: Cannot invoke "java.sql.Connection.createStatement()" because "con" is null
	at org.postgresql.test.TestUtil.dropTable(TestUtil.java:547)
	at org.postgresql.test.jdbc42.GetObject310Test.tearDown(GetObject310Test.java:75)
```

/cc @BaurzhanSakhariev

**Comment by matriv** [comment]
Seems that we never run the tests in past?
Probably we have to replace all `:jdbc:postgresql:` urls with `:jdbc:crate:`?

**Comment by mfussenegger** [comment]
We run the tests we need as part of crate-jdbc, and it's more or less frozen as we push towards using stock PostgreSQL JDBC.
